# Generated by Django 4.0.3 on 2022-03-25 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('body', models.TextField(max_length=6000000)),
                ('Hacker', models.CharField(max_length=250)),
                ('pubDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=6000000)),
                ('Hacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Challenges.challenges')),
            ],
        ),
    ]
